### ISSUE TITLE
Feedback: TItles & Name too Dark + Search Redundant

### ISSUE THREAD

**Issue by w4rner** [microdotblog/plugin-marfa-dark#1]
<img width="1087" alt="Screen Shot 2020-10-17 at 2 56 20 PM" src="https://user-images.githubusercontent.com/31451410/96338968-6bcb9480-1089-11eb-8ff5-d9b5d64f42b0.png">
<img width="1028" alt="Screen Shot 2020-10-17 at 2 56 42 PM" src="https://user-images.githubusercontent.com/31451410/96338967-6a01d100-1089-11eb-8fc6-aefcca8361fd.png">

didnt realise it was you who made this lol Manton

**Comment by w4rner** [comment]
Also some images appear to big: 
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/31451410/96339420-7dfb0200-108c-11eb-8b4f-c2a63be4b0fa.png">
from https://w4rner-test.micro.blog/2020/10/12/goodreads-isnt-good.html

**Comment by w4rner** [comment]
Of things mentioned @stettgames :
- dark names fixed. But not titles on Archive page.

Relatedly on new one:
light comments on light background aren't different enough: 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/31451410/120689002-8aa55c80-c49b-11eb-930e-38235c88b3e7.png">

- can't speak to auto-image sizing. It certainly got automatically better when I switched to Typewriter (dark) (original link still works). Not sure if now better on Marfa or if need to manually resize images. 

- kept DDG as search. Could Marfa not get a similar in-blog search like Typewriter ([e.g.](https://blog.w4rner.com/search))

**Comment by manton** [comment]
I think we can close this now. The latest version of the plug-in has been updated. Thanks y'all!
